services:
  sgtdb-dock:
    image: postgres
    ports:
      - "5431:5432"
    container_name: "sgtdb-dock"
    restart: always
    volumes:
      - ./bd-backup:/var/lib/postgresql/data
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    # volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgtdb
  
  app:
    build: 
      context: .
    stdin_open: true
    tty: true
    command: yarn start
    depends_on:
      - sgtdb-dock
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@sgtdb-dock:5432/sgtdb?schema=public"
    ports:
      - "2504:2504"

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  bd-backup: